//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPParseHub
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActiveJockey
    {
        public int ID { get; set; }
        public Nullable<int> JockeyID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string County { get; set; }
        public string Postcode { get; set; }
        public string Phone { get; set; }
        public string LicenseType { get; set; }
        public string Fname { get; set; }
    }
}
