//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPParseHub
{
    using System;
    using System.Collections.Generic;
    
    public partial class BH_Sale
    {
        public int Id { get; set; }
        public Nullable<int> Year { get; set; }
        public string Type { get; set; }
        public string SaleHipType { get; set; }
        public string NameSexYOB { get; set; }
        public string Pedigree { get; set; }
        public string Cover { get; set; }
        public string Buyer { get; set; }
        public string Consignor { get; set; }
        public string Price { get; set; }
        public string Status { get; set; }
        public Nullable<int> Processed { get; set; }
        public string Sale { get; set; }
        public string Hip { get; set; }
        public string SaleType { get; set; }
        public string Horse { get; set; }
        public string Sex { get; set; }
        public Nullable<int> FoalYear { get; set; }
        public string Sire { get; set; }
        public string Dam { get; set; }
        public string DamSire { get; set; }
        public Nullable<int> PriceUSD { get; set; }
    }
}
