//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPParseHub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public int class1 { get; set; }
        public Nullable<int> PreviousClass { get; set; }
        public Nullable<int> NextClass { get; set; }
    }
}
