//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPParseHub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Going
    {
        public int Id { get; set; }
        public string Brief { get; set; }
        public string Description { get; set; }
        public Nullable<int> GroupId { get; set; }
        public string ShortBrief { get; set; }
        public Nullable<int> NextGoingGroupID { get; set; }
        public Nullable<int> PrevGoingGroupID { get; set; }
    }
}
