//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPParseHub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horse_Merged
    {
        public int Id { get; set; }
        public Nullable<int> RHId { get; set; }
        public Nullable<int> PPId { get; set; }
        public string Name { get; set; }
        public string PPName { get; set; }
        public string PPFlatName { get; set; }
        public string Country { get; set; }
        public Nullable<System.DateTime> FoalDate { get; set; }
        public Nullable<int> FoalYear { get; set; }
        public string Colour { get; set; }
        public string Sex { get; set; }
        public Nullable<int> SireId { get; set; }
        public Nullable<int> DamId { get; set; }
        public Nullable<bool> GroupWinner { get; set; }
        public Nullable<bool> StakesWinner { get; set; }
        public string Haplo { get; set; }
        public string ShortRaceInfo { get; set; }
        public string MergeBasis { get; set; }
    }
}
