//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPParseHub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meeting
    {
        public int Id { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<System.DateTime> DateOfMeeting { get; set; }
        public string Going { get; set; }
        public string Weather { get; set; }
        public string Stalls { get; set; }
        public Nullable<bool> RaceWithFences { get; set; }
        public Nullable<int> PAId { get; set; }
    }
}
