//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPParseHub
{
    using System;
    using System.Collections.Generic;
    
    public partial class MissedMatchesPQ
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string FlatName { get; set; }
        public string PQ_Country { get; set; }
        public string PP_Country { get; set; }
        public Nullable<int> PQ_FoalYear { get; set; }
        public Nullable<int> PP_FoalYear { get; set; }
        public string PQ_SireId { get; set; }
        public string PP_Sire { get; set; }
        public string PQ_DamId { get; set; }
        public string PP_Dam { get; set; }
    }
}
