//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPParseHub
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RacingPostRacesEntities : DbContext
    {
        public RacingPostRacesEntities()
            : base("name=RacingPostRacesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RPCourse> RPCourses { get; set; }
        public virtual DbSet<RPHorse> RPHorses { get; set; }
        public virtual DbSet<Jockey> Jockeys { get; set; }
        public virtual DbSet<Meeting> Meetings { get; set; }
        public virtual DbSet<RPRace> RPRaces { get; set; }
        public virtual DbSet<RaceGroup> RaceGroups { get; set; }
        public virtual DbSet<RaceType> RaceTypes { get; set; }
        public virtual DbSet<RPRunner> RPRunners { get; set; }
        public virtual DbSet<ScrapeCourse> ScrapeCourses { get; set; }
        public virtual DbSet<ScrapeRace> ScrapeRaces { get; set; }
        public virtual DbSet<TrackType> TrackTypes { get; set; }
        public virtual DbSet<Trainer> Trainers { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<Going> Goings { get; set; }
        public virtual DbSet<ActiveJockey> ActiveJockeys { get; set; }
        public virtual DbSet<ActiveTrainer> ActiveTrainers { get; set; }
        public virtual DbSet<AgeOfRace> AgeOfRaces { get; set; }
        public virtual DbSet<BH_Sale> BH_Sale { get; set; }
        public virtual DbSet<ClassGroup> ClassGroups { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Horse_Merged> Horse_Merged { get; set; }
        public virtual DbSet<PA_Course> PA_Course { get; set; }
        public virtual DbSet<PA_Meeting> PA_Meeting { get; set; }
        public virtual DbSet<PA_TrackDirection> PA_TrackDirection { get; set; }
        public virtual DbSet<PP_Horse> PP_Horse { get; set; }
        public virtual DbSet<PQ_Horse> PQ_Horse { get; set; }
        public virtual DbSet<PQ_HorseTemp> PQ_HorseTemp { get; set; }
        public virtual DbSet<ReportPermutation> ReportPermutations { get; set; }
        public virtual DbSet<ScrapeBH> ScrapeBHs { get; set; }
        public virtual DbSet<HorseRacingAnalysi> HorseRacingAnalysis { get; set; }
        public virtual DbSet<MissedMatchesPQ> MissedMatchesPQs { get; set; }
        public virtual DbSet<PA_Address> PA_Address { get; set; }
        public virtual DbSet<PA_Race> PA_Race { get; set; }
        public virtual DbSet<Sample> Samples { get; set; }
        public virtual DbSet<Season> Seasons { get; set; }
        public virtual DbSet<SummaryQuery2> SummaryQuery2 { get; set; }
    }
}
