//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPParseHub
{
    using System;
    using System.Collections.Generic;
    
    public partial class PA_Meeting
    {
        public int Id { get; set; }
        public string Status { get; set; }
        public Nullable<int> FeedId { get; set; }
        public string Country { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string DrawnAdvantage { get; set; }
        public string AdvancedGoing { get; set; }
        public string Weather { get; set; }
    }
}
