//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPParseHub
{
    using System;
    using System.Collections.Generic;
    
    public partial class PA_Race
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> ScheduledOffTime { get; set; }
        public Nullable<System.DateTime> ActualOffTime { get; set; }
        public Nullable<int> PenaltyFundId { get; set; }
        public Nullable<int> AddedMoneyFundId { get; set; }
        public Nullable<int> Distance { get; set; }
        public string Weather { get; set; }
        public Nullable<bool> Handicap { get; set; }
        public Nullable<bool> Trifecta { get; set; }
        public Nullable<int> FeedId { get; set; }
        public Nullable<int> RaceTypeId { get; set; }
        public string Class { get; set; }
        public Nullable<int> MaxRunners { get; set; }
        public Nullable<bool> ShowCase { get; set; }
        public Nullable<int> Revision { get; set; }
        public Nullable<int> GoingId { get; set; }
        public string Status { get; set; }
        public string Eligibility { get; set; }
        public Nullable<int> LastWinnerId { get; set; }
        public Nullable<int> BetMarketId { get; set; }
        public string Message { get; set; }
        public Nullable<int> MeetingId { get; set; }
        public Nullable<decimal> WinTime { get; set; }
        public string GoingDescription { get; set; }
        public Nullable<int> TrackDirectionId { get; set; }
        public Nullable<int> StandardTimeId { get; set; }
        public Nullable<decimal> GoingAllowance { get; set; }
        public Nullable<int> LastYearID { get; set; }
    }
}
