//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPParseHub
{
    using System;
    using System.Collections.Generic;
    
    public partial class PP_Horse
    {
        public int id { get; set; }
        public string name { get; set; }
        public string flatname { get; set; }
        public Nullable<System.DateTime> dateofbirth { get; set; }
        public string familynumber { get; set; }
        public Nullable<System.DateTime> yearofdeath { get; set; }
        public string countryoffoalingid { get; set; }
        public string colourid { get; set; }
        public string genderid { get; set; }
        public string shortraceinfoid { get; set; }
        public Nullable<int> noofstarts { get; set; }
        public Nullable<int> noofwins { get; set; }
        public Nullable<int> noof2nds { get; set; }
        public Nullable<int> noof3rds { get; set; }
        public Nullable<int> bestbhb { get; set; }
        public Nullable<int> bestform { get; set; }
        public Nullable<int> bestts { get; set; }
        public string mtdnahaplotype { get; set; }
        public string totalprizemoney { get; set; }
        public string winprizemoney { get; set; }
        public Nullable<int> trainerid { get; set; }
        public Nullable<int> ownerid { get; set; }
        public Nullable<int> breederid { get; set; }
        public Nullable<int> sireid { get; set; }
        public Nullable<int> damid { get; set; }
        public string comments { get; set; }
        public Nullable<bool> isactualdate { get; set; }
        public Nullable<bool> iscustom { get; set; }
        public string lastcreatedby { get; set; }
        public Nullable<System.DateTime> lastcreateddate { get; set; }
        public string lastmodifiedby { get; set; }
        public Nullable<System.DateTime> lastmodifieddate { get; set; }
        public Nullable<bool> ishypo { get; set; }
        public Nullable<bool> i { get; set; }
        public Nullable<bool> c { get; set; }
        public Nullable<bool> s { get; set; }
        public Nullable<bool> p { get; set; }
        public Nullable<bool> b { get; set; }
        public Nullable<int> randseq { get; set; }
        public Nullable<bool> hasraced { get; set; }
        public Nullable<int> height { get; set; }
        public string heightunit { get; set; }
        public Nullable<int> birthweight { get; set; }
        public string birthweightunit { get; set; }
        public Nullable<bool> ispedigreecomplete { get; set; }
        public string salesid { get; set; }
        public Nullable<bool> twin { get; set; }
        public Nullable<int> pq_starts { get; set; }
        public Nullable<int> pq_wins { get; set; }
        public Nullable<int> pq_places { get; set; }
        public string pq_earnings { get; set; }
        public string pq_owner { get; set; }
        public string pq_breeder { get; set; }
    }
}
