//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPParseHub
{
    using System;
    using System.Collections.Generic;
    
    public partial class PQ_Horse
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string FlatName { get; set; }
        public string Country { get; set; }
        public Nullable<int> FoalYear { get; set; }
        public string Colour { get; set; }
        public string Sex { get; set; }
        public string SireId { get; set; }
        public string DamId { get; set; }
        public Nullable<int> Starts { get; set; }
        public Nullable<int> Wins { get; set; }
        public Nullable<int> Places { get; set; }
        public string Earnings { get; set; }
        public string Owner { get; set; }
        public string Breeder { get; set; }
        public Nullable<bool> SexRescrape { get; set; }
        public Nullable<bool> SexRescrape1 { get; set; }
        public Nullable<int> MergeId { get; set; }
        public string MergeMatchBasis { get; set; }
        public string PQOutcome { get; set; }
    }
}
