//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPParseHub
{
    using System;
    using System.Collections.Generic;
    
    public partial class RaceGroup
    {
        public int ID { get; set; }
        public int RaceID { get; set; }
        public int GroupID { get; set; }
    }
}
