//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPParseHub
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportPermutation
    {
        public int ID { get; set; }
        public string Criteria { get; set; }
        public Nullable<int> Races { get; set; }
        public Nullable<int> Winners { get; set; }
        public Nullable<int> Runners { get; set; }
        public Nullable<decimal> Qualified_Winners { get; set; }
        public Nullable<decimal> Wins_Losses { get; set; }
        public Nullable<decimal> PandLTotal { get; set; }
        public Nullable<decimal> PandLPercent { get; set; }
    }
}
