//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPParseHub
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPHorse
    {
        public int Id { get; set; }
        public Nullable<int> RPId { get; set; }
        public string Name { get; set; }
        public string FlatName { get; set; }
        public string Country { get; set; }
        public Nullable<System.DateTime> FoalDate { get; set; }
        public Nullable<int> FoalYear { get; set; }
        public string PedigreeRaw { get; set; }
        public Nullable<int> PedigreeProcessed { get; set; }
        public string DetailRaw { get; set; }
        public Nullable<int> DetailProcessed { get; set; }
        public string Colour { get; set; }
        public string Sex { get; set; }
        public Nullable<int> SireId { get; set; }
        public Nullable<int> DamId { get; set; }
        public Nullable<bool> GroupWinner { get; set; }
        public Nullable<bool> StakesWinner { get; set; }
        public Nullable<int> PPId { get; set; }
        public string PPMatchBasis { get; set; }
        public string PQId { get; set; }
        public string PQMatchBasis { get; set; }
        public string PQOutcome { get; set; }
        public string Backfill { get; set; }
        public string Haplo { get; set; }
        public string PPRaceInfo { get; set; }
        public bool PriorityProcess { get; set; }
        public bool LaterProcess { get; set; }
        public string flatname1 { get; set; }
        public string flatsire { get; set; }
        public string flatdam { get; set; }
        public Nullable<int> belid { get; set; }
        public Nullable<bool> PostTemplate { get; set; }
        public string Breeder { get; set; }
    }
}
