//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPParseHub
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPRace
    {
        public int Id { get; set; }
        public Nullable<int> MeetingId { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public string Name { get; set; }
        public Nullable<int> RaceType { get; set; }
        public Nullable<int> Season { get; set; }
        public string SeasonType { get; set; }
        public Nullable<bool> Handicap { get; set; }
        public Nullable<bool> Chase { get; set; }
        public Nullable<bool> Hurdle { get; set; }
        public Nullable<bool> NHFlat { get; set; }
        public string ClassRaw { get; set; }
        public Nullable<int> ClassProcessed { get; set; }
        public Nullable<int> Class { get; set; }
        public string GradeGroup { get; set; }
        public string Rating { get; set; }
        public string Eligibility { get; set; }
        public string TrackDirection { get; set; }
        public Nullable<int> DistanceYards { get; set; }
        public string Distance { get; set; }
        public string DistanceStd { get; set; }
        public string Going { get; set; }
        public string FencesHurdles { get; set; }
        public Nullable<int> Fences { get; set; }
        public Nullable<int> FencesOmitted { get; set; }
        public string PrizeMoney { get; set; }
        public Nullable<decimal> Prize1st { get; set; }
        public Nullable<decimal> Prize2nd { get; set; }
        public Nullable<decimal> Prize3rd { get; set; }
        public Nullable<decimal> Prize4th { get; set; }
        public Nullable<decimal> Prize5th { get; set; }
        public Nullable<decimal> Prize6th { get; set; }
        public Nullable<int> Runners { get; set; }
        public string Time { get; set; }
        public Nullable<double> TimeSeconds { get; set; }
        public Nullable<double> DiffStandard { get; set; }
        public string Notes { get; set; }
        public string NonRunners { get; set; }
        public Nullable<int> CourseId { get; set; }
        public string CurrencyUnit { get; set; }
        public Nullable<bool> PostTemplate { get; set; }
        public Nullable<int> NoOfRunners { get; set; }
        public string TotalSP { get; set; }
    }
}
