//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPParseHub
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPRunner
    {
        public int Id { get; set; }
        public Nullable<int> HorseId { get; set; }
        public Nullable<int> RaceId { get; set; }
        public string Status { get; set; }
        public Nullable<int> Position { get; set; }
        public Nullable<int> Placed { get; set; }
        public string DidNotFinish { get; set; }
        public Nullable<bool> Disqualified { get; set; }
        public Nullable<int> Draw { get; set; }
        public string Distance { get; set; }
        public Nullable<double> DistBeaten { get; set; }
        public string Price { get; set; }
        public Nullable<bool> PriceProcessed { get; set; }
        public Nullable<int> Numerator { get; set; }
        public Nullable<int> Denominator { get; set; }
        public Nullable<bool> Favourite { get; set; }
        public string WeightRaw { get; set; }
        public Nullable<int> WeightProcessed { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<int> Weight_OW { get; set; }
        public Nullable<int> Weight_OH { get; set; }
        public Nullable<int> Weight_EW { get; set; }
        public string Weight_Desc { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> TrainerId { get; set; }
        public Nullable<int> JockeyId { get; set; }
        public Nullable<int> Allowance { get; set; }
        public Nullable<int> Rating { get; set; }
        public string OR_Rating { get; set; }
        public string TS_Rating { get; set; }
        public string RPR_Rating { get; set; }
        public string Comments { get; set; }
        public Nullable<int> HorseRaceSequence { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public Nullable<bool> PostTemplate { get; set; }
    }
}
