//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPParseHub
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScrapeRace
    {
        public int Id { get; set; }
        public int MeetingId { get; set; }
        public string Link { get; set; }
        public Nullable<bool> Scraped { get; set; }
        public Nullable<int> RaceId { get; set; }
        public Nullable<System.DateTime> RaceDate { get; set; }
        public string CourseUrl { get; set; }
        public Nullable<bool> Required { get; set; }
        public string Country { get; set; }
    }
}
