//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPParseHub
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScrapeBH
    {
        public int Id { get; set; }
        public Nullable<int> Year { get; set; }
        public string Type { get; set; }
        public string Url { get; set; }
        public Nullable<bool> Scraped { get; set; }
    }
}
