//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPParseHub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Season
    {
        public int Id { get; set; }
        public Nullable<int> RaceType { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public Nullable<int> Season1 { get; set; }
        public string SeasonType { get; set; }
    }
}
